# Generated by Django 4.2 on 2023-04-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('nombreComuna', models.CharField(max_length=45, verbose_name='Comuna')),
                ('idComuna', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=40, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('codigoProducto', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('nombreDireccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('codigoPostal', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Postal')),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigoCompra', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código de compra')),
                ('fechaCompra', models.DateField()),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.direccion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre')),
                ('emailCliente', models.CharField(max_length=50, verbose_name='Email')),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.compra')),
            ],
        ),
    ]
